levels = {
    "easy": 10,
    "normal": 25,
    "hard": 50,
    "random": 15
}

quiz = {
    "easy": [
        {"question": "The Earth is round.", "answer": True},
        {"question": "The Sun rises in the east.", "answer": True},
        {"question": "Water is wet.", "answer": True},
        {"question": "2 + 2 equals 4.", "answer": True},
        {"question": "Cats are animals.", "answer": True},
        {"question": "Dogs can fly naturally.", "answer": False},
        {"question": "The sky is green.", "answer": False},
        {"question": "Humans need oxygen to live.", "answer": True},
        {"question": "Ice is hot.", "answer": False},
        {"question": "Fish live in water.", "answer": True},

        {"question": "The Moon is made of cheese.", "answer": False},
        {"question": "Fire is cold.", "answer": False},
        {"question": "Trees are plants.", "answer": True},
        {"question": "Birds have wings.", "answer": True},
        {"question": "The Earth has one Sun.", "answer": True},
        {"question": "1 is greater than 2.", "answer": False},
        {"question": "Apples are fruits.", "answer": True},
        {"question": "The ocean is dry.", "answer": False},
        {"question": "Humans can breathe underwater without equipment.", "answer": False},
        {"question": "Day follows night.", "answer": True},

        {"question": "The Sun is hot.", "answer": True},
        {"question": "Snow is cold.", "answer": True},
        {"question": "Cars can fly like birds.", "answer": False},
        {"question": "Water falls from clouds as rain.", "answer": True},
        {"question": "A triangle has three sides.", "answer": True},
        {"question": "A square has five sides.", "answer": False},
        {"question": "Fish can walk on land naturally.", "answer": False},
        {"question": "The Earth has gravity.", "answer": True},
        {"question": "Books contain stories or information.", "answer": True},
        {"question": "Fire produces light.", "answer": True},

        {"question": "A year has 365 days (usually).", "answer": True},
        {"question": "Humans have hands.", "answer": True},
        {"question": "The sky is usually blue.", "answer": True},
        {"question": "Elephants are tiny.", "answer": False},
        {"question": "Milk comes from cows.", "answer": True},
        {"question": "The Earth is flat.", "answer": False},
        {"question": "Ice melts when heated.", "answer": True},
        {"question": "A circle has corners.", "answer": False},
        {"question": "Shoes are worn on hands.", "answer": False},
        {"question": "Rain comes from clouds.", "answer": True},

        {"question": "Humans walk on two legs.", "answer": True},
        {"question": "The Sun is a planet.", "answer": False},
        {"question": "Water is a liquid at room temperature.", "answer": True},
        {"question": "Stars shine at night.", "answer": True},
        {"question": "A car is a vehicle.", "answer": True},
        {"question": "Bread is a type of fruit.", "answer": False},
        {"question": "A week has 7 days.", "answer": True},
        {"question": "Fire is made of ice.", "answer": False},
        {"question": "Humans can live without food forever.", "answer": False},
        {"question": "The Earth rotates.", "answer": True},
    ],

    "normal": [
        {"question": "The Earth orbits the Sun.", "answer": True},
        {"question": "Venus is the hottest planet in the solar system.", "answer": True},
        {"question": "Water boils at 100°C at sea level.", "answer": True},
        {"question": "The human body has 300 bones.", "answer": False},
        {"question": "Sound travels faster than light.", "answer": False},
        {"question": "The Pacific Ocean is the largest ocean.", "answer": True},
        {"question": "Sharks are mammals.", "answer": False},
        {"question": "The human heart has four chambers.", "answer": True},
        {"question": "Mercury is the closest planet to the Sun.", "answer": True},
        {"question": "Bats are birds.", "answer": False},

        {"question": "DNA carries genetic information.", "answer": True},
        {"question": "The Eiffel Tower is in London.", "answer": False},
        {"question": "Plants produce oxygen through photosynthesis.", "answer": True},
        {"question": "Sound can travel in a vacuum.", "answer": False},
        {"question": "The Earth has one natural satellite.", "answer": True},
        {"question": "Humans are amphibians.", "answer": False},
        {"question": "Gold is a chemical element.", "answer": True},
        {"question": "Mount Everest is the tallest mountain above sea level.", "answer": True},
        {"question": "The Sun is a star.", "answer": True},
        {"question": "Pluto is classified as a dwarf planet.", "answer": True},

        {"question": "Fish use lungs to breathe.", "answer": False},
        {"question": "Oxygen is essential for human life.", "answer": True},
        {"question": "The human skeleton is made of over 200 bones.", "answer": True},
        {"question": "Lightning is a form of electricity.", "answer": True},
        {"question": "All insects have 8 legs.", "answer": False},
        {"question": "The Amazon is a rainforest and river system.", "answer": True},
        {"question": "Humans have five basic senses.", "answer": True},
        {"question": "The speed of light is faster than sound.", "answer": True},
        {"question": "A triangle always has 4 sides.", "answer": False},
        {"question": "The brain controls the body.", "answer": True},

        {"question": "The Moon produces its own light.", "answer": False},
        {"question": "Water is H2O.", "answer": True},
        {"question": "Steel is an element.", "answer": False},
        {"question": "The liver is an organ in the human body.", "answer": True},
        {"question": "Mars is known as the Red Planet.", "answer": True},
        {"question": "The Milky Way is a galaxy.", "answer": True},
        {"question": "Humans can survive without water for weeks easily.", "answer": False},
        {"question": "The Earth has a molten core.", "answer": True},
        {"question": "Octopuses have three hearts.", "answer": True},
        {"question": "The Sahara is the largest desert on Earth.", "answer": True},

        {"question": "All bacteria are harmful.", "answer": False},
        {"question": "Venus rotates in the opposite direction of most planets.", "answer": True},
        {"question": "Ice is denser than liquid water.", "answer": False},
        {"question": "The lungs are part of the respiratory system.", "answer": True},
        {"question": "Humans share DNA with bananas.", "answer": True},
        {"question": "Gold rusts easily.", "answer": False},
        {"question": "Sound needs a medium to travel.", "answer": True},
        {"question": "The Earth is older than 4 billion years.", "answer": True},
        {"question": "A year always has 365 days exactly.", "answer": False},
        {"question": "Salt dissolves in water.", "answer": True},
    ],

    "hard": [
        {"question": "The speed of light in vacuum is constant.", "answer": True},
        {"question": "Neutrons carry a positive charge.", "answer": False},
        {"question": "Humans have more bacterial cells than human cells.", "answer": True},
        {"question": "Black holes can emit light.", "answer": True},
        {"question": "ATP is the energy currency of cells.", "answer": True},
        {"question": "Electrons are larger than protons.", "answer": False},
        {"question": "The brain has no pain receptors.", "answer": True},
        {"question": "Quantum particles can exist in superposition.", "answer": True},
        {"question": "The universe is estimated to be over 13 billion years old.", "answer": True},
        {"question": "DNA is made of proteins.", "answer": False},

        {"question": "Sound waves are electromagnetic waves.", "answer": False},
        {"question": "The human genome contains 23 pairs of chromosomes.", "answer": True},
        {"question": "Absolute zero is 0 Kelvin.", "answer": True},
        {"question": "Light behaves only as a particle.", "answer": False},
        {"question": "The mitochondria is the powerhouse of the cell.", "answer": True},
        {"question": "Neurons are muscle cells.", "answer": False},
        {"question": "Covalent bonds involve sharing electrons.", "answer": True},
        {"question": "Earth’s core is entirely solid.", "answer": False},
        {"question": "The periodic table is arranged by atomic number.", "answer": True},
        {"question": "Time dilation occurs in relativity.", "answer": True},

        {"question": "Dark matter can be directly observed with light.", "answer": False},
        {"question": "Entropy tends to increase in isolated systems.", "answer": True},
        {"question": "RNA is identical to DNA.", "answer": False},
        {"question": "Sound travels faster in steel than air.", "answer": True},
        {"question": "The speed of sound is constant in all media.", "answer": False},
        {"question": "Hydrogen is the most abundant element in the universe.", "answer": True},
        {"question": "Protons are made of quarks.", "answer": True},
        {"question": "The human eye can see infrared light.", "answer": False},
        {"question": "Fusion powers the Sun.", "answer": True},
        {"question": "Atoms are mostly empty space.", "answer": True},

        {"question": "The Heisenberg uncertainty principle is exact.", "answer": True},
        {"question": "Light has mass at rest.", "answer": False},
        {"question": "Magnetic fields are produced by moving charges.", "answer": True},
        {"question": "Neptune is closer to the Sun than Uranus.", "answer": False},
        {"question": "The universe is expanding.", "answer": True},
        {"question": "Energy can be created from nothing.", "answer": False},
        {"question": "All planets in the solar system orbit in perfect circles.", "answer": False},
        {"question": "Carbon is a basis for life on Earth.", "answer": True},
        {"question": "Gamma rays have the highest energy in the EM spectrum.", "answer": True},
        {"question": "Space is completely empty.", "answer": False},
    ]
}
